name: Java CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test

      - name: Generate code coverage report
        run: ./gradlew jacocoTestReport

      - name: Check code coverage
        run: ./gradlew jacocoTestCoverageVerification

  check-failing-tests:
    needs: build
    runs-on: ubuntu-latest
    if: always() # always execute this job
    steps:
      - name: Check failing tests
        run: exit 1 # To simulate test failure

  check-code-coverage:
    needs: build
    runs-on: ubuntu-latest
    if: always() # always execute this job
    steps:
      - name: Check code coverage threshold
        run: exit 2 # To simulate insufficient code coverage failure
