name: Java CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: "17"
      - name: Build with Gradle
        run: ./gradlew build
      - name: Run tests
        run: |
          set +e
          ./gradlew test
          TEST_EXIT_CODE=$?
          if [ $TEST_EXIT_CODE -ne 0 ]; then
            exit 1
          fi
      - name: Generate code coverage report
        run: ./gradlew jacocoTestReport
      - name: Check code coverage
        run: |
          ./gradlew jacocoTestCoverageVerification
          COVERAGE_EXIT_CODE=$?
          if [ $COVERAGE_EXIT_CODE -ne 0 ]; then
            exit 2
          fi
  check-failing-tests:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check failing tests
        run: exit 1
    if: failure()
  check-code-coverage:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check code coverage threshold
        run: exit 2
    if: always()
